name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_wuEqigl8lbthaf6zeX1VL8g3
          vercel-project-id: prj_6XYHfONBqIsw7eqjVargxoo7kgYz
          vercel-args: '--prod'
